### ISSUE TITLE
Add support for Docker Compose 

### ISSUE THREAD

**Issue by OpenPj** [OpenPj/alfresco-process-services-project-sdk#2]
The Alfresco Community is asking to add Docker support:
https://hub.alfresco.com/t5/alfresco-process-services/alfresco-process-services-sdk-maven-module/bc-p/296035#M339

It should be easy to extend the SDK with this capabilities using the docker-maven-plugin provided by fabric8io:
https://github.com/fabric8io/docker-maven-plugin

We could follow the same approach I used in the Keycloak Docker Quickstart where I used the same plugin:
https://github.com/OpenPj/keycloak-docker-quickstart

**Comment by jpotts** [comment]
I also would like to see a Docker-based SDK for APS. What you have started here is good, but I feel like it exposes a lot of nuts-and-bolts to the developer that they may not need to see. If we use a Docker approach instead, maybe project instances of the SDK can be streamlined because they will not need to include the libraries and configuration necessary to actually run Activiti.

**Comment by OpenPj** [comment]
I agree with you @jpotts and recently I implemented something very useful for Activiti 5 Community (not Open Source at the moment) so I could just follow the same approach using the official Docker images provided by Alfresco for executing a very clean overlay process for any custom extension.

I hope to find some time to work on this during the next weeks 😅

**Comment by OpenPj** [comment]
Added support for doing overlayed WAR with extensions JAR with Docker container building in the latest 1.3.0 that is the same in the main trunk:
https://github.com/OpenPj/alfresco-process-services-project-sdk/releases/tag/v1.3.0
